### ISSUE TITLE
help with install

### ISSUE THREAD

**Issue by Kite-Smurf** [custom-cards/bar-card#101]
Is there any way you could give me more detailed instruction on how to install the Bar Card?
I tried searching for it in HACS with no luck.
Thanks for help in advance.

**Comment by Gluwc** [comment]
Should be in HACS, have a look at https://github.com/custom-cards/bar-card#installation

**Comment by Kite-Smurf** [comment]
I'm sorry, the info on the github link ( https://github.com/custom-cards/bar-card#installation ) might be super clear for very experienced users, but it does not make sens to me. Searching in HACS for bar or card or bar-card does not return the proper hit for the bar-card. 

Trying to add custom repository with link does not allow selecting type: module so this is also not clear:
- url: /hacsfiles/bar-card/bar-card.js
  type: module

So, a little more details about how get the bar-card installed would be very much appreciated.
Thanks for help in advance.

**Comment by Kite-Smurf** [comment]
I got it working finally.

Thanks for creating this card type really cool !!!

**Comment by antoweb** [comment]
Can you explain how to install?

**Comment by Kite-Smurf** [comment]
1. Install HACS
2. in Home Assistant Community Store go to Frontend
3. Search for: Bar Card
4. hit install

**Comment by antoweb** [comment]
I have already HACS but i cant find bar card only timer bar card
![Screenshot_2021-11-01-12-37-36-559_io homeassistant companion android](https://user-images.githubusercontent.com/32364871/139665844-78791adb-0da2-4e82-b492-757eb0734b5c.jpg)

**Comment by Kite-Smurf** [comment]
I installed it quite some time ago and I'm not sure if I had to do more than this.

![image](https://user-images.githubusercontent.com/59253744/139668540-36434af5-e1be-4fdb-9864-a2dc5e8c7532.png)
