### ISSUE TITLE
[Feature request] display complementary value

### ISSUE THREAD

**Issue by amaximus** [custom-cards/bar-card#102]
I'd like to request a feature for displaying complementary to max value while the bar uses the sensor state value.

Let's take the car oil change as example:
- oil change interval is 20000km => min: 0, max: 20000
- last change was at 40000km (last_change_km)
- now we are at 53000km (current_km)
- the sensor would report  current_km-last_change_km

The bar-card (min:0, max: 20000) should display the bar as 53000-40000 (13000; this would be provided by the sensor) while the value displayed should be the complementary to max, 20000-13000 (7000).

So the complementary value to display should be:  max - states.sensor.example.state

BTW thanks for this great card.

**Comment by Gluwc** [comment]
Added in 3.2.0, thanks for the PR!
