### ISSUE TITLE
bar-card.js asset for release 1.3.0 doesn't contain minmax code

### ISSUE THREAD

**Issue by TheLastProject** [custom-cards/bar-card#11]
I was wondering why HACS wasn't showing my minmax stuff until I realized it's not actually in the assets for that release: https://github.com/custom-cards/bar-card/releases/tag/1.3.0

See https://github.com/custom-cards/bar-card/releases/download/1.3.0/bar-card.js and search for "show_minmax". It isn't there.

**Comment by Gluwc** [comment]
Should be fixed now, thanks for reporting.
