### ISSUE TITLE
Custom element doesn't exist: bar-card.

### ISSUE THREAD

**Issue by gmarjano1975** [custom-cards/bar-card#114]
Hi,
I installed the bar-card using HACS and restarted HA. I tried it with a simple card:
```
type: 'custom:bar-card'
entity: sensor.climate_buro_rssi_device
title: Severity
```

It does not work. I get the error: Custom element doesn't exist: bar-card.
The resource is integrated in the Lovelace Configuration....

I use the following versions:

HASSIO: Home Assistant OS 5.9
HA: 2020.12.7
HACS: 1.9.0 (Frontend: 20201205162459)

**Comment by Finagain** [comment]
Same exact Issue as gmarjano1975

Version | 2020.12.0 <--Apparently there is an update! :)
-- | --
Installation Type | Home Assistant Container

Installed HACS yesterday.

Thank you!

**Comment by Finagain** [comment]
My issue fixed itself.  I changed nothing and today it works! Thanks you.

**Comment by gmarjano1975** [comment]
Works again....

**Comment by IIIdefconIII** [comment]
i have this as of today on the latest HA

**Comment by IIIdefconIII** [comment]
does anyone if this card should still work? im getting this error too

**Comment by ildar170975** [comment]
Works fine on my setup.

**Comment by IIIdefconIII** [comment]
> Works fine on my setup.

would you have some sparte time to look at my setup? perhaps on discord sreen share?
Im probably doing something wrong, messing this game a few days now :)

**Comment by ildar170975** [comment]
Discord is not accessible in my country. Also, currently I am very far from a PC for a long period.
General suggestion - try purging your browser cache, check if all resources are properly used. Are you using HACS to install the card?

**Comment by IIIdefconIII** [comment]
> Discord is not accessible in my country. Also, currently I am very far from a PC for a long period. General suggestion - try purging your browser cache, check if all resources are properly used. Are you using HACS to install the card?
Im not seeying that card an hacs anymore, yes i did purged the cache all time, excapt for cookies which should be needit i believe

<img width="1429" height="452" alt="Image" src="https://github.com/user-attachments/assets/4cfc4d0e-1963-4314-b631-d53c2692d74d" />

**Comment by ildar170975** [comment]
Yes, the card was removed from HACS, we should be grateful to this stupid issue - https://github.com/hacs/integration/issues/4172.
No idea why people are so idiotic. The card is absolutely functional.
Look at HACS PRs section, it is full of similar "I am not using the card anymore, I cannot use it, the last update was a year ago, my very important issue is not solved - so remove the card for everyone".

Try to add this card as a custom repository to HACS.
There is a corr. menu (right top corner), input an address `https://github.com/custom-cards/bar-card` & type `dashboard module` (or whatever it is called).
Installing cards via HACS is a more convenient way of installing plugins, HACS will notify you when a plugin is updated & also takes care of a proper registering of resources.

**Comment by IIIdefconIII** [comment]
> Yes, the card was removed from HACS, we should be grateful to this stupid issue - [hacs/integration#4172](https://github.com/hacs/integration/issues/4172). No idea why people are so idiotic. The card is absolutely functional. Look at HACS PRs section, it is full of similar "I am not using the card anymore, I cannot use it, the last update was a year ago, my very important issue is not solved - so remove the card for everyone".
> 
> Try to add this card as a custom repository to HACS. There is a corr. menu (right top corner), input an address `https://github.com/custom-cards/bar-card` & type `dashboard module` (or whatever it is called). Installing cards via HACS is a more convenient way of installing plugins, HACS will notify you when a plugin is updated & also takes care of a proper registering of resources.

thanks the card does load now so thanks for that, but the percentage isnt working, im not a coder otherwise i would try to fix it

**Comment by ildar170975** [comment]
Suggest to ask a question in HA community, perhaps it is an easy thing.

**Comment by IIIdefconIII** [comment]
> Suggest to ask a question in HA community, perhaps it is an easy thing.

tbh as the card isnt updated for 2 years i just let it go and take the hue card instead

**Comment by ildar170975** [comment]
There are many cards which have not been updated for several years and yet keep working.
As I said, the card is fully functional, but it is up to you whether to use it or not.

**Comment by IIIdefconIII** [comment]
> There are many cards which have not been updated for several years and yet keep working. As I said, the card is fully functional, but it is up to you whether to use it or not.

got ya, at least thank you alot bringing me this far!
