### ISSUE TITLE
card does not render is null entity

### ISSUE THREAD

**Issue by jchasey** [custom-cards/bar-card#12]
I have the card render ink levels, however if the sensors with the ink levels fail to initialise (e.g. the printer is off when HA starts) then the card stops the whole view from being rendered and you a left with a blank screen.
Could the entities be checked that they are non-null and appropriate error be displayed?

**Comment by Gluwc** [comment]
This is possibly fixed in the latest version, could you check and confirm?

**Comment by jchasey** [comment]
Unfortunately not. 
It does appear to throw an error message that I hadn't noticed before:

`https://xxx.co.uk/community_plugin/bar-card/bar-card.js:971:36 Uncaught Error: sensor.ink_level_black doesn't exist.
`

**Comment by Gluwc** [comment]
Hopefully [1.4.1](https://github.com/custom-cards/bar-card/releases/tag/1.4.1) fixes it. Did some quick tests and seems to be working for me, please confirm.

**Comment by jchasey** [comment]
Yes, that stops the view crashing, many thanks!
