### ISSUE TITLE
Feature request: Use negative/positive rage and start the bar at zero

### ISSUE THREAD

**Issue by RonnyWinkler** [custom-cards/bar-card#178]
I like this bar. But I have issues to get a nice layout using a min/max range with negative values.

Example:
I would like to use the bar to show battery usage in Watt für the PV system (negative: charging, positive: dischanging).
With min:-4000 and max:4000 I can define a range to show. But the bar is started at the left border, not in the middle (at zero):
![grafik](https://github.com/custom-cards/bar-card/assets/49495550/33b8973e-d04c-487a-ad0b-1dae5f8a3dde)

Could it be possible (or extended) to show the bar from the zero value like this example?
![grafik](https://github.com/custom-cards/bar-card/assets/49495550/d3f98bd3-aecb-4e87-939d-24d91bc98ea2)

**Comment by PulsarFX** [comment]
same as  #143 ?

**Comment by RonnyWinkler** [comment]
Yes, it's the same. I missed the other request. So this duplicate can be closed.
