### ISSUE TITLE
NaN value in bar card

### ISSUE THREAD

**Issue by klaasnicolaas** [custom-cards/bar-card#19]
Since the 1.5.0 version, my hassio version sensor in the bar-card no longer wants to show the value, but `NaN` appears. While if I click on it, I will just see the correct value and if I put the entry somewhere else in my lovelace config it goes fine too.

![image](https://user-images.githubusercontent.com/20448157/63195523-1a81d880-c073-11e9-809b-3824f105f99a.png)
![image](https://user-images.githubusercontent.com/20448157/63195541-2b324e80-c073-11e9-841f-556efacb38c8.png)

Running Hassio: 0.97.2
Also tested release 1.5.2 and same problem

The lovelace code I used can be [found here](https://github.com/klaasnicolaas/Student-homeassistant-config/blob/master/lovelace/views/system.yaml#L25)

**Comment by klaasnicolaas** [comment]
Don't know why but for some reason the bar-card works fine, so I will close this issue ✅

**Comment by klaasnicolaas** [comment]
Reopen my issue. The same problem now occurs on my 2nd home assistant installation and also with the installation of a friend of mine 🤔

**Comment by mossburg145** [comment]
.Same problem, here also/

**Comment by fsteccanella** [comment]
It's because of: https://github.com/custom-cards/bar-card/blob/1a9ffb1b3a845300b6982ea62f563006a9a2c742/bar-card.js#L1018

The state "0.97.2" is NaN

**Comment by klaasnicolaas** [comment]
I have installed the new version and removed the cache but the problem persists.

**Comment by ezraholm50** [comment]
Same

**Comment by Gluwc** [comment]
This should really be fixed in 1.5.4.

![image](https://user-images.githubusercontent.com/38736396/63418674-c9bc0800-c403-11e9-9ec8-3a571ef13631.png)

If it's not working for you please check your console log to make sure you're running the latest version.

![image](https://user-images.githubusercontent.com/38736396/63418802-012ab480-c404-11e9-9ee6-68140733207d.png)

**Comment by klaasnicolaas** [comment]
I have checked my console log but it still indicates 1.5.2, weird because I did do an upgrade in HACS to the 1.5.4 version. How can I solve this?

**Comment by Gluwc** [comment]
I've been having issues with HACS as well where it won't update/clear my cache. Reinstalling the plugin worked for me.

**Comment by klaasnicolaas** [comment]
I have completely removed the bar-card, reinstalled it and removed the cache. I can now confirm that the problem has been solved 🎉
