### ISSUE TITLE
tap_action error

### ISSUE THREAD

**Issue by madmicio** [custom-cards/bar-card#25]
code:

tap_action: service
service_options:
  service: input_select.select_option
  data:
    entity_id: input_select.cover_select
    option: option_name

error:

Error handling message: required key not provided @ data['domain']. Got None

can you help me?
where am i wrong?

**Comment by Gluwc** [comment]
At appears you're missing the data field. Have a look at the documentation: https://github.com/custom-cards/bar-card#service-call

**Comment by madmicio** [comment]
service: select_option
domain: input_select

**Comment by Gluwc** [comment]
Not sure if this is resolved, but I can't reproduce the error myself with the correct config.
