### ISSUE TITLE
custom-cards org

### ISSUE THREAD

**Issue by iantrich** [custom-cards/bar-card#3]
Invitation to bring your repo over to the community custom-cards organization: https://github.com/custom-cards/information

Let me know if you're interested and I can float you an invitation to the org. Thanks!

**Comment by Gluwc** [comment]
Hey Ian, thanks for the invite but I've already moved it over a couple days ago 😀. Jack invited me to the org last week or so.

**Comment by iantrich** [comment]
...oh my gosh, I didn't even notice the redirect when I went here from sharethelove.io :rofl: AWESOME! Welcome!
