### ISSUE TITLE
"Cannot add property x, object is not extensible" [Solved - issue with HACS update]

### ISSUE THREAD

**Issue by SamPhoenix91** [custom-cards/bar-card#32]
Version 1.7.1 on HA 0.106.2

Items do not appear to be defaulting, need to add each property manually.

"Cannot add property x, object is not extensible" where x is each property that I do not declare

**Comment by SamPhoenix91** [comment]
Originally updated via HACS, manually updating fixed it, so there is something wrong with the HACS update

**Comment by Martinvdm** [comment]
I do still have this issue. Did an manual update by downloading 1.7.1 .js file to the folder, but does not solved it. How did you solved this?
