### ISSUE TITLE
All cards gave error

### ISSUE THREAD

**Issue by fssantos95** [custom-cards/bar-card#34]
Hello. Today I check my cards and all of them said this:
![image](https://user-images.githubusercontent.com/57115015/75812658-7fd6b600-5d86-11ea-817f-001e5a9c30fb.png)

can you help?

**Comment by Gluwc** [comment]
You need to update to version [1.7.1](https://github.com/custom-cards/bar-card/releases/tag/1.7.1). Make sure you clear your cache and check the console of your browser to make sure you're running the latest version.
