### ISSUE TITLE
Bar-graph on top of each other?

### ISSUE THREAD

**Issue by fribse** [custom-cards/bar-card#36]
This is related to the other question I had to the other with the corona sensor (this is just as an example).
The sensor provides four numbers:

confirmed
cured
recovered
ill

Where the first number is the total of the other three.

Is it possible to have a bar where the other numbers sort of mark the fraction of the total (stacked bar chart)?

**Comment by Gluwc** [comment]
There's currently no way to have multiple sensors displayed in a single bar. This would require some rework of the card, which I don't really have to time for right now unfortunately.

**Comment by Gluwc** [comment]
This is unfortunately not a feature I would like to implement, specially since [3.0.0](https://github.com/custom-cards/bar-card/releases/tag/3.0.0) now tries simplify the amount if features supported.
