### ISSUE TITLE
"Cannot add property direction, object is not extensible" in HA 0.106.6

### ISSUE THREAD

**Issue by opep** [custom-cards/bar-card#37]
Red box with the above statement.
It is probably related to new changes since 0.106 affecting custom cards.
More details here:
https://developers.home-assistant.io/blog/2020/02/18/106-custom-card-changes/
I will take the opportunity to thank you for the card, hoping that it can be solved easily and soon,
Thanks.

**Comment by Gluwc** [comment]
This is fixed in 1.7.1

**Comment by madmicio** [comment]
same problem, 
if i insert the bar card into a entities card i recive the same error, 
if my strucure is:

```
entity-card
  card-mod
    bard-bard 
```

all ok
