### ISSUE TITLE
Conditional title color

### ISSUE THREAD

**Issue by Sonusss** [custom-cards/bar-card#38]
Isn't it possible to define conditional text color ?

For example like this:
title_style: 
   color: >
      {% if is_state('switch.sonoff_p3', 'ON') %}  red {% else %} green  {% endif %}

**Comment by Gluwc** [comment]
This is possible in [3.0.0](https://github.com/custom-cards/bar-card/releases/tag/3.0.0) with a combination of https://github.com/iantrich/config-template-card and https://github.com/thomasloven/lovelace-card-mod.
