### ISSUE TITLE
Icon to replace title?

### ISSUE THREAD

**Issue by kloggy** [custom-cards/bar-card#4]
Would it be possible to have the icon _replace_ the title I.e. be outside the bar, and then have the value positioned left, right or centre within the bar?

**Comment by Gluwc** [comment]
This currently isn't possible, I'll have a look and see what I can do to make this a feature.

**Comment by tungmeister** [comment]
I'd love this as well. If it could be formatted like a normal entity with the icon then title followed by the bar that would be great.

**Comment by Gluwc** [comment]
1.2.0 now has the option to set `icon_position`
