### ISSUE TITLE
Columns option gone?

### ISSUE THREAD

**Issue by rpitera** [custom-cards/bar-card#43]
Was the columns: option taken out?  If so, why and is there another way to do this now?

**Comment by daniele-athome** [comment]
I second this. Don't get me wrong, you're doing a great job, but you should really put some more examples out there, including a minimal explanation of the various CSS classes that we can customize with card-mod (I'm going through the source code and browser developer tools now, it's a major barrier of entry).

Thanks for bar-card!

**Comment by Gluwc** [comment]
The columns option is now replaced by the `stack` option, however this is a bit more limited as it only stacks every bar in the config and doesn't start new rows.

Also I'm working on adding some more examples and documentation on the CSS customization.

However I don't completely agree it's a huge barrier to entry. Maybe if you used the card before and you don't have as many out of the box options now it might be a bit more work, but out of the box this card should now be easier to use.

**Comment by rpitera** [comment]
> The columns option is now replaced by the stack option, however this is a bit more limited as it only stacks every bar in the config and doesn't start new rows.

I'm guessing that you meant to say doesn't start new _columns_, am I correct?   I guess I would have to do two separate cards now in a horizontal stack to reproduce what I had before.  Not terrible, but it seems like a step backward instead of forward.  Also I can't seem to figure out how to override CSS to keep my bars from inheriting the theme's border-radius which was never an issue before.  I had it fixed for the last release but this release reverted everything back again.

While I wouldn't go so far as to call it a major barrier of entry, I would also say that the last two releases have made it harder instead of easier to do layouts like I had.  Hopefully your example additions will help me figure it out though.

Would appreciate next time if you labeled breaking changes though!  Thanks.

**Comment by Gluwc** [comment]
The breaking changes including the columns was noted in the 3.0.0 release notes, although the columns breaking changes could have possibly used some more detail.

Also the theme values and CSS elements are now inlcuded in the documentation. https://github.com/custom-cards/bar-card#theme-variables

If you need any more help with getting things back to or close to what they were before let me know.

**Comment by rpitera** [comment]
Thanks for the replies and help.  I'll take a shot at things today.  In any event, I appreciate both your hard work on this as well as the reasoning behind the changes.

**Comment by rpitera** [comment]
So I finally got this to work, but it meant splitting my one card into, each with half the entries, then nesting them into a horizontal stack card.  I had to apply separate styles to each card to fix padding as well.  

So while it was not unfixable, it also required a whole lot of YAML and CSS lines to accomplish what I used to do with a single option.  So I don't see it being easier to use in the long run, but then I don't view it from a dev's perspective.  Could you share your reasoning for this change in approach?  I don't mean it to sound ungrateful - I am certainly not and I love this card.  I just want to understand better so I learn more and can share that knowledge.

Totally up to you if you want to reply or not; if not close the issue and it's done.  Otherwise, just leave it open and reply whenever you feel like it.  Either way, thanks for the work!

**Comment by Gluwc** [comment]
I was already considering putting this back in because I kind of agree it's annoying. The main reason is mostly to simplify the card a bit, but obviously this causes concerns with people already using certain features. If I could release the card from scratch I probably would have left out some features.
Another reason was due to the fact that the way the card is now structured it's a bit more complicated to get the columns working properly. I'll have a look this weekend to see if I can find a simpler way of re-implementing it.

**Comment by daniele-athome** [comment]
Thanks @Gluwc for your suggestions, I'll apply some of your suggestions to make it work - I'll probably follow the lead @rpitera (thank you too by the way).

**Comment by rpitera** [comment]
I mean, it's working fine for me now so if simplifying the feature set makes it easier for you to maintain the project, I'm all for it.  My line of questioning wasn't intended to ask you to 'justify' your decisions in any way; I just benefit from understanding why devs do what devs do and when I help others (I'm a mod in the forums as well as in the HomeAutomation subreddit and contribute daily to the HA subreddit) I can then pass that knowledge on.  Hopefully this leads to less issues posted here if I can answer some.   So I appreciate your explaining it.

If you like the challenge and want to return the feature - awesome.  If not,  I hope that it makes it easier for you to maintain it as keeping it alive and growing is my goal as well.  Cheers!

**Comment by rpitera** [comment]
> I'll probably follow the lead @rpitera (thank you too by the way).

@daniele-athome - If it helps at all, this was the styling piece I was missing to keep my bar graphs from inheriting my theme's border-radius:

```
style: | 
  ha-card {
   --bar-card-border-radius: 0px;
  }
```

**Comment by Gluwc** [comment]
You're probably better off adding that variable to your theme instead so you don't have to set that style for every card.

Anyway I've added `columns` back in to [3.0.6](https://github.com/custom-cards/bar-card/releases/tag/3.0.6). Took a bit of extra brain power, but I managed to get it to work in the end xD.

**Comment by rpitera** [comment]
Thanks so much for restoring this feature, Lucas.  Very much appreciated!

**Comment by daniele-athome** [comment]
Thank you both guys.
