### ISSUE TITLE
Get the target marker without change of colors at the rest of the bar.

### ISSUE THREAD

**Issue by Ndrinta** [custom-cards/bar-card#44]
Hi everyone,
I'm trying to customize the CSS to get a bar with the target-marker but without shift in color of the the rest of the bar. Just like if the only difference between the regular one and the one with target option enabled was the line of the marker itself and nothing more.
I'm playing with `bar-card-targetbar` and `bar-card-targetmarker` CSS options but I can't see any changes at all, no matter what I do to them.
Can someone help me out here? Or, if I'm using the wrong approach, what else could I try?

Many thanks for every little help!

PS: My card looks like this...
```
style: |-
  bar-card-targetbar {
    # bla bla
  }
  bar-card-targetmarker {
    # bla bla
  }
```

**Comment by Gluwc** [comment]
This should work:
```yaml
style: |-
  bar-card-targetbar {
    visibility: hidden;
  }
```

**Comment by Ndrinta** [comment]
Didn't do the job unfortunately....
This is the default:
![image](https://user-images.githubusercontent.com/4704172/78701852-9a5cfb80-78ff-11ea-9616-25f970b76dc9.png)
This is with your `style` option:
![image](https://user-images.githubusercontent.com/4704172/78702002-d2643e80-78ff-11ea-86f5-29f4c760daf2.png)

**Comment by Gluwc** [comment]
Are you sure you have card-mod installed? These options aren't default.

**Comment by Ndrinta** [comment]
Oh shoot.
Let me see...

**Comment by Ndrinta** [comment]
Oh shoot.
Let me see...

Update: That was it! I was still missing that piece of the puzzle.
Mega thanks to you sir @Gluwc !

**Comment by Gluwc** [comment]
No worries! It looks great, I like your theme even though I'm a dark mode andy. Always nice to see your hard work put to good use.

**Comment by Ndrinta** [comment]
Oh, right, now that you make me notice I have to test the style mod in the dark theme to...
I've got the automation set to switch between light/dark theme based on the sun. 😉

**Comment by Gluwc** [comment]
You actually made me notice I fucked up the positions on the direction up mode. I would actually like to fix it but that might change your layout a bit. You'll still be able to get this exact layout back with a little bit more CSS styles though.
