### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by pipetboy** [custom-cards/bar-card#45]
I'm confused about the Title. You can specify the Title in the Header. But Title is also used to display the friendly name of the entity.
Title: 'off'  # means no friendly name. 
I want to add CSS to the Header (to change the font size and the padding). 
It used to be that I could just specify the title-style. Why has that been removed?

Thank you for all your work. The card is great to look at!

**Comment by Gluwc** [comment]
`title` is now only used for the header. If you want to change the name inside the card use `name`.

Also if you want to change any CSS in the card now you'll have to use card-mod. Have a look at the docs https://github.com/custom-cards/bar-card/blob/master/README.md#css-elements .

**Comment by pipetboy** [comment]
Thank you for your response.
I am using the card-mod. It works great! But that is not the issue.

In positions: Title changes the location of the NAME
In CSS: bar-card-title refers to the NAME
Do you see my confusion?

Why not use Header for Title?

Thank you for your work!

**Comment by Gluwc** [comment]
Right I see what you mean. This is mostly to keep the options in line with the default cards like [entities card](https://www.home-assistant.io/lovelace/entities/).
Also I'm actually using parts of the default HA elements to add the header, so it also renders the same as the default card.
So if you want to change anything on the header use:

```
.card-header {
  font-size: 10px;
}
```

**Comment by pipetboy** [comment]
Thank you so much for your work.

I ended up going with your first suggestion and using the name, and positioning that as a header. 

I'm happy! ;)


![Theo custom bar card](https://user-images.githubusercontent.com/54765387/78881701-77455f80-7a57-11ea-9526-6f0fdb14af33.jpg)
`            - type: custom:bar-card
              entity: sensor.atag_one_room_temp
              direction: up
              name: Kamer
              decimal: 1
              positions:
                title: inside
                icon: 'off'
                indicator: inside
              severity:
                - color: rgb(0,0,255)
                  from: 13
                  to: 17.9
                - color: rgb(0,128,255)
                  from: 18
                  to: 18.9
                - color: rgb(204,102,0)
                  from: 19
                  to: 19.9
                - color: rgb(204,51,0)
                  from: 20
                  to: 20.9
                - color: rgb(255,0,0)
                  from: 21
                  to: 25
              height: 105px
              width: 95%
              min: 13
              max: 25
              style: |-
                bar-card-value {
                  font-size: 35px;
                  position: absolute;
                  bottom: 0px;
                }
                bar-card-title {
                  position: absolute;
                  top: 0px;
                  left: 5px;
                  font-size: 20px;
                }
                .card-content {
                  padding: 0px;
                }
                bar-card-indicator {
                  position: absolute;
                  top: 3px;
                  left: 90%;
                  font-size: 20px;
                }`
