### ISSUE TITLE
Add a sensor as a Target 

### ISSUE THREAD

**Issue by gw1gw1** [custom-cards/bar-card#53]
Hi,

Thanks for the card, it is really awesome and it really helps enhancing my views.

I am using this bar-card for my NUT sensors and I have two sensors I wanted to combine into one car card. First is the Current battery level and second is the low battery set point.

I created a bar-card for my Current battery level and I wanted to add the second sensor as my target but I could not as it only allows numbers.

The easy workaround is to input the number of my sensor as it is a static value but I was wondering if this is something you would consider.

Not critical but nice to have.

Thanks

**Comment by Gluwc** [comment]
Hey hey! This is already possible with the help of [template-card](https://github.com/iantrich/config-template-card). It allows you to use any entity value from HA as an input for a config. So I probably won't be adding this to the card.

**Comment by gw1gw1** [comment]
Thanks. Did not think of that. I will have a look.

Thanks and great job for the card
