### ISSUE TITLE
BUG: Error loading card

### ISSUE THREAD

**Issue by firstof9** [custom-cards/bar-card#56]
Error message:
```
Uncaught SyntaxError: Unexpected token 'export' bar-card.js:5219
```
Home Assistant: 0.108.9
I've already clear cache and hard reloaded the frontend but the issue persists.

Let me know if you need any more information.

**Comment by D-an-W** [comment]
Similar here...

http://hassio.local:8123/community_plugin/bar-card/bar-card.js:5219:0 SyntaxError: Unexpected keyword 'export'
3:36:45 AM – components/system_log/__init__.py (ERROR)

**Comment by Gluwc** [comment]
I'm unable to reproduce this, so my only guess is it might be browser related? I've only tested it on chrome, maybe you're using something else?

**Comment by D-an-W** [comment]
Safari here

**Comment by Klumpke** [comment]
@D-an-W since version 3.1.0 you need to use `type: module` instead of `type: js` in your resources.

**Comment by D-an-W** [comment]
Thank you, will edit now.

**Comment by Gluwc** [comment]
> @D-an-W since version 3.1.0 you need to use `type: module` instead of `type: js` in your resources.

Didn't even know it was still possible to set this up as `type: js`, maybe if you had it loaded as JS before  they deprecated it?

**Comment by Klumpke** [comment]
Don't know. Had it loaded as `type: js` before and with version 3.1.0 this didn't work so i had changed it to `type: module`

**Comment by D-an-W** [comment]
I wish I knew where to change it! haha

**Comment by Gluwc** [comment]
The resrouces are now loaded seperately from the lovelace config. It's in Configuration>Lovelace Dashboards>Resources.

**Comment by D-an-W** [comment]
Sorted thanks, are they bigger than before or just my imagination?

![Screenshot 2020-04-25 at 12 23 20](https://user-images.githubusercontent.com/2243883/80278584-926acd00-86ef-11ea-92dc-4efb85962347.png)

**Comment by Gluwc** [comment]
I don't know what it looked like before for you. However there were some changes with the `title` and `name` config options that might have changed the look of you card. (`title` now adds a header instead of changing the `name` of the bar).

**Comment by firstof9** [comment]
I use HACS to manage it all guess it didn't change to module. Thank you.

**Comment by ldb2000** [comment]
Could be good to add in the the readme.md
