### ISSUE TITLE
 export declarations may only appear at top level of a module

### ISSUE THREAD

**Issue by tomlut** [custom-cards/bar-card#58]
Since updating to  3.1.0 I have been receiving this error in the log:
```
ERROR (MainThread) [frontend.js.latest.202004072] https://my_domain.duckdns.org/hacsfiles/bar-card/bar-card.js:5219:0 SyntaxError: export declarations may only appear at top level of a module
```
And the card no longer displays in the front end. I get the dreaded red:` Custom element doesn't exist: bar-card`. I have tried reloading the browser cache without success. 

Reverting to version 3.0.9 and reloading the browser cache rectifies the issue.

**Comment by Gluwc** [comment]
I haven't seen this specific error before. Are you sure the card is loaded as a `module` in your resources?

**Comment by tomlut** [comment]
I'd check but sine HACS no longer stores that information in the Lovelace file I have no idea where to look.

Somewhere in .storage?

**Comment by Gluwc** [comment]
It's been moved to Configuration>Lovelace Dashboard>Resources. (which means it's in .storage yes)

**Comment by tomlut** [comment]
Changed it to Javascript Module in the UI, updated, refreshed the cache and all seems to be well. 

I guess I should check the others while I'm there. 

Thanks you.
