### ISSUE TITLE
Width not working

### ISSUE THREAD

**Issue by zejulio** [custom-cards/bar-card#59]
Hello,

I've followed some examples and this one:

entity: sensor.example
positions:
  icon: 'off'
  indicator: inside
  title: outside
type: 'custom:bar-card'
width: 70%
title: 2.0.0 Default Layout
style: |-
  bar-card-value {
    margin-right: auto;
    font-size: 13px;
    font-weight: bold;
    text-shadow: 1px 1px #0005;
  }

Does not return as the image, the width property is not working.
I use 100%, 10% and it always use the full row...
I have card-mod installed...
Thanks for the great work!

**Comment by Gluwc** [comment]
I need to update that example since it's outdated. If you replace `title: outside` with `name: outside` the width should work.

Currently the card width only really works when the `direction` is `up` or when the `name` position is `outside`.

**Comment by zejulio** [comment]
I found that by trying the GUI card.
Ended up working as I wanted. Thanks for the good work!
