### ISSUE TITLE
Add condition to be able to hide the bar

### ISSUE THREAD

**Issue by lispwarez** [custom-cards/bar-card#60]
In some cases it may be nice to be able to hide a bar depending on certain conditions.

In my case I use your card to show current power consumption and generation(solar). At night the solar graph is at 0 so it would be nice to hide that graph during this period

**Comment by Gluwc** [comment]
I'll see if I can add something like `hidden: true` to the severity.

**Comment by Gluwc** [comment]
Added in [3.1.2](https://github.com/custom-cards/bar-card/releases/tag/3.1.2). You can set `hide: true` on the severity config option now.

```yaml
severity:
  - from: '0'
    to: '0'
    hide: true
```
