### ISSUE TITLE
bar card load error

### ISSUE THREAD

**Issue by scooper1** [custom-cards/bar-card#61]
any idea why i am getting 
[frontend.js.latest.202004240] https://scrts.duckdns.org:8123/hacsfiles/bar-card/bar-card.js:5219:1 Uncaught SyntaxError: Unexpected token 'export'

running current 109 beta
have hard reset chrome 
only happening on one system 
running newest bar card

**Comment by Gluwc** [comment]
You have to load the resource as a module instead of js.

**Comment by pjmaenh** [comment]
Had the same issue, card not found and error in logs. import as module solved this for me

**Comment by scooper1** [comment]
Thanks that worked
