### ISSUE TITLE
Card height not reported correctly to frontend

### ISSUE THREAD

**Issue by tomlut** [custom-cards/bar-card#62]
The card height does not appear to be reported to the frontend correctly. resulting in layouts like this:

![Screenshot_2020-04-27 Overview - Home Assistant(1)](https://user-images.githubusercontent.com/10679300/80406632-cefc1b80-88dd-11ea-85ce-dc508bc3403c.png)

**Comment by tomlut** [comment]
Still seeing this with 3.1.3 (the browser window is zoomed out to see all the cards, but there is horizontal room for 4 columns as evidenced in all my other views). 

![Untitled](https://user-images.githubusercontent.com/10679300/80679546-7d6ab100-8ad6-11ea-9524-7b6a34df9112.png)

**Comment by Gluwc** [comment]
Should be fixed in [3.1.4](https://github.com/custom-cards/bar-card/releases/tag/3.1.4).

**Comment by tomlut** [comment]
It is indeed fixed. Thanks again!

**Comment by tomlut** [comment]
This issue seems to have pooped up again, not sure how long it has been going on but I am on 2021.7.4.

**Comment by tomlut** [comment]
Never mind. My Mistake. Had the card inside an entities card.
