### ISSUE TITLE
Card Bar issues - icon positions & bar sizes

### ISSUE THREAD

**Issue by cubandanger05** [custom-cards/bar-card#64]
**On v3.1.2, the icon position 'outside' shows icon inside the card bar:**

![icon outside](https://user-images.githubusercontent.com/63987200/80415271-4e6afa00-88a0-11ea-87f2-6c760b8ffae7.png)

**For vertical bar, the size is completely off; both examples in the screenshot below are using icon position 'inside':**

![wrong size](https://user-images.githubusercontent.com/63987200/80415460-95f18600-88a0-11ea-9cc1-69782fae83cf.png)

**Comment by Gluwc** [comment]
The first issue is a bug I need to fix. For the second issue did you set a bar height? Also could your provide me with your yaml config for this card and maybe a screenshot of what it looked like before?

**Comment by cubandanger05** [comment]
See below

Copy of yaml

animation:
  state: 'off'
decimal: '0'
direction: up
entities:
  - entity: sensor.memory_use
    name: Used
    positions:
      icon: inside
    severity:
      - color: Green
        from: '0'
        to: '999'
      - color: Orange
        from: '1000'
        to: '1599'
      - color: Red
        from: '1600'
        to: '2000'
  - decimal: '0'
    entity: sensor.memory_free
    min: 0
    name: Available
    positions:
      icon: inside
    severity:
      - color: Red
        from: '0'
        to: '400'
      - color: Orange
        from: '401'
        to: '1000'
      - color: Green
        from: '1001'
        to: '2000'
height: 50px
max: '1857'
min: '0'
positions:
  icon: 'off'
  indicator: 'off'
  minmax: 'off'
  name: outside
  title: outside
  value: outside
stack: horizontal
title: RAM - 2GB
type: 'custom:bar-card'
unit_of_measurement: MB
width: 55px

**Comment by Gluwc** [comment]
Looks like the height is now set for the whole card including the text now when set to `up`, instead of the height of the bar part. I'll see if I can fix this.

**Comment by cubandanger05** [comment]
Glad you could pinpoint the problem. Thank you for looking into it.

**Comment by Gluwc** [comment]
This should be fixed in [3.1.3](https://github.com/custom-cards/bar-card/releases/tag/3.1.3)

**Comment by cubandanger05** [comment]
Thank you. Confirmed working.
