### ISSUE TITLE
issue with stacking

### ISSUE THREAD

**Issue by dartfrogdk** [custom-cards/bar-card#66]
version 3.09
![2020-04-29-Overview - Home Assistant – Google Chrome](https://user-images.githubusercontent.com/29755226/80595589-44becf00-8a25-11ea-918c-a923a0e78960.png)

version 3.12
![2020-04-29-Overview - Home Assistant – Google Chrome_2](https://user-images.githubusercontent.com/29755226/80595607-4d170a00-8a25-11ea-8659-98a08da147af.png)

**Comment by Gluwc** [comment]
Try removing `stack: vertical` they should already be stacked vertical by default and I think there's an issue with setting it to vertical, but I'll need to have a look.

**Comment by dartfrogdk** [comment]
worked thanx

**Comment by Gluwc** [comment]
Fixed in [3.1.4](https://github.com/custom-cards/bar-card/releases/tag/3.1.4).
