### ISSUE TITLE
Unexpected token 'export' error

### ISSUE THREAD

**Issue by jamesking420** [custom-cards/bar-card#70]
The following error regularly pops up in my logs, but I don't know why?  :-)
```
Log Details (ERROR)
Logger: frontend.js.latest.202004271
Source: components/system_log/__init__.py:209
First occurred: 6:31:30 AM (4 occurrences)
Last logged: 11:06:57 AM

https://my.custom.domain/hacsfiles/bar-card/bar-card.js:5340:1 Uncaught SyntaxError: Unexpected token 'export'
```
(I've replaced my domain here but obviously it's correct in the original error message.).

**Comment by Gluwc** [comment]
Have a look at this https://community.home-assistant.io/t/lovelace-bar-card/87503/488?u=gluwc
