### ISSUE TITLE
No longer works inside Layout-card

### ISSUE THREAD

**Issue by codeclinic** [custom-cards/bar-card#71]
I’m running HASSIO and everything was fine until a couple of updates ago. Since then all my bar-cards have stopped being displayed. Now I just get the big red box of doom saying;

    Custom element doesn’t exist: bar-card

I’m using the custom:layout-card by Thomas Lovren. Bar cards displayed outside of this appear to work fine.

Any ideas what’s wrong & how to fix it?

Thanks.

**Comment by Gluwc** [comment]
I'm unable to reproduce this and I'm running the latest version of layout-card and bar-card. Maybe you don't have the resource loaded as a module? Otherwise I don't really have a clue.

**Comment by codeclinic** [comment]
It would appear that the problem is actually when using the bar-card inside custom:vertical-stack-in-card.

Theres another person on the HA forum confirming the same thing: 
https://community.home-assistant.io/t/lovelace-bar-card/87503/504

**Comment by Gluwc** [comment]
This is probably more an issue with vertical-stack-in-card. As far as I know that card is no longer being maintained and has been replaced by stack-in-card.

**Comment by codeclinic** [comment]
Ok, I'll take a look at that.

Thanks.

**Comment by codeclinic** [comment]
I'm getting the same issue with stack-in-card.

**Comment by Gluwc** [comment]
Could you post your config, I'm still unable to reproduce this.

**Comment by volpmatt** [comment]
I'm getting the red box error with `Custom element doesn’t exist: bar-card` wherever I put the card in my config. It doesn't seem to be related to any layout or stack card. Config hasn't changed since updating to 0.109.

**Comment by codeclinic** [comment]
@volpmatt Have you made sure that both bar-card & card-tools are set as module type rather than js ? I made that change and bar-card now seems to be working.

**Comment by drthanwho** [comment]
> @volpmatt Have you made sure that both bar-card & card-tools are set as module type rather than js ? I made that change and bar-card now seems to be working.

This fixed it for me
