### ISSUE TITLE
Request - Change colour based on state

### ISSUE THREAD

**Issue by Shaun-Harrison** [custom-cards/bar-card#72]
Hi

Wondering if its possible to have the bar colour change based on a state?

So I'm using the bar to display a phones battery percentage, would be nice to have it turn a certain colour if the phone is on charge based on a sensor state

Or at least, if the value is increasing instead of decreasing its a certain colour?

Thank you!

**Comment by Gluwc** [comment]
This isn't directly possible with the card config, but you can probably change the `color` value of the bar using [config-template-card](https://github.com/iantrich/config-template-card).

**Comment by Shaun-Harrison** [comment]
No problem, will check this out, thank you!
