### ISSUE TITLE
Bar-card no longer showing

### ISSUE THREAD

**Issue by bouwew** [custom-cards/bar-card#75]
As reported by others and me in the Community-topic, starting from 0.109.0(?).

I also see this error in Logs:
`http://192.168.xxx.yyy:8123/local/community/bar-card/bar-card.js:5349:1 Uncaught SyntaxError: Unexpected token 'export'`

**Comment by Gluwc** [comment]
Please have a look at the breaking changes https://github.com/custom-cards/bar-card/releases/tag/3.1.0

**Comment by bouwew** [comment]
Yeah, I missed that one, thanks!
