### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by anglrus** [custom-cards/bar-card#78]
Hello,
I have got error: 
Cannot read property 'length' of undefined for variant with direction UP. Example does'not have such parameter. I tried to add this parameter. Error is the same

          - type: 'custom:bar-card'
            entity: sensor.xiaomi_air_humidifier_2_depth
            title: Direction
            direction: up
            height: 200px
            stack: horizontal

Thank you

**Comment by SNoof85** [comment]
Why do you add the stack attibute as you have only 1 bar ?

Remove this and your problem is solved !
