### ISSUE TITLE
error/warning about index.m.js.map

### ISSUE THREAD

**Issue by Mariusthvdb** [custom-cards/bar-card#79]
please check https://community.home-assistant.io/t/failed-to-load-resource-index-m-js-map-what-is-this/193292 for a community discussion about an error/warning about an index.m.js.map file the bar-card seems to expect.

adding an empty file with the name changes the error in to a warning, but still shouldn't be there?

thanks for having a look

<img width="613" alt="Schermafbeelding 2020-05-06 om 13 41 04" src="https://user-images.githubusercontent.com/33354141/81303364-e4aad700-907b-11ea-9c89-b1a071d5a99f.png">

<img width="748" alt="Schermafbeelding 2020-05-07 om 16 01 11" src="https://user-images.githubusercontent.com/33354141/81303506-10c65800-907c-11ea-8012-12642e07c743.png">

note I didn't have the resources in their own folder yet while I encountered the error, so the bar-card isn't mentioned  yet. after having changed that, and created the file (empty) the warning clearly states bar-card.

**Comment by andriej** [comment]
Same issue in 0.110.1, still.

**Comment by chemelli74** [comment]
Noticed this issue, only after opening a similar one: #85 

Simone

**Comment by Mariusthvdb** [comment]
and on 0.111.2
did the author ever recognize this issue?

**Comment by MACscr** [comment]
Doesnt appear that he has. That stinks that its been going on for so long.

**Comment by Spankythemusical** [comment]
Here's a "fix".  Go to /home/homeassistant/.homeassistant/www/community/bar-card and open bar-card.js with your editor of choice.
Do a search for index.m.js.map (only one instance and should be at the end of line 2967).
Position cursor before //# and press enter.  This will put it on a new line and in some editors change the color.
So on line 2968 you will end up with "//# sourceMappingURL=index.m.js.map"
This should be commented out, but being at the end of the previous line makes it part of the code and the system doesn't know how to handle it.
Clear browser cache and reload HA page.

**Comment by Gluwc** [comment]
Should be fixed in [3.1.7](https://github.com/custom-cards/bar-card/releases/tag/3.1.7).
