### ISSUE TITLE
Icon & title alignment and dynamic width?

### ISSUE THREAD

**Issue by tungmeister** [custom-cards/bar-card#8]
Hi, would it be possible to get the alignment of the text and icon to always be fixed to the left - similar to how other entities work? at the moment it looks like below when they're included:
![image](https://user-images.githubusercontent.com/127809/58030676-d84e0700-7b16-11e9-8fbf-40408990cca1.png)
without locking the width of the bar to 65% it would end up looking like this which is totally unusable as the text can't be read and the icon becomes extremely small - if the bar could have an option to dynamically resize based on title length that would be great.:
![image](https://user-images.githubusercontent.com/127809/58030755-003d6a80-7b17-11e9-86a6-8147f5827d78.png)

**Comment by Gluwc** [comment]
To be fair I've only tested icon or title, not both. This would require a bit more of a rework, but shouldn't be too hard to do I guess.

**Comment by tungmeister** [comment]
I'd greatly appreciate the title and icon issue being resolved, the dynamic width of the bar wouldn't be a major concern for me, it was more of an observation that other users may desire, as you said dynamic scaling would cause different sizes which could be an issue when directly comparing but if it was an individual instance wouldn't cause an issue.

**Comment by Gluwc** [comment]
The alignment should be fixed in [1.2.1](https://github.com/custom-cards/bar-card/releases/tag/1.2.1). The dynamic scaling will take a bunch more work and is something I might consider for a later release, but for now you'll have to scale them yourself.
