### ISSUE TITLE
FR: allow top of current bar to use border-radius

### ISSUE THREAD

**Issue by Mariusthvdb** [custom-cards/bar-card#81]
HI, 

building on this community discussion https://community.home-assistant.io/t/remove-border-space-of-cards/195262/22?u=mariusthvdb it would be really cool if we could also round the currentbar, instead of this right now:

<img width="419" alt="Schermafbeelding 2020-05-15 om 13 58 50" src="https://user-images.githubusercontent.com/33354141/82048318-c2850a80-96b4-11ea-9059-0400539873a1.png">

all credits for the card to @hajo62 

thanks for considering!

**Comment by Gluwc** [comment]
As petro already mentioned in the community thread, this would require a lot of re-working of the bar layout since I'm using a gradient for the current bar. Unfortunately not something I have time for right now.
