### ISSUE TITLE
Add an header text to the card

### ISSUE THREAD

**Issue by gigios** [custom-cards/bar-card#9]
There is a way to add a title to the card (not a title to a single bar)?

**Comment by Gluwc** [comment]
This is probably not something I will have time to add any time soon. I would recommend using [button-card](https://github.com/custom-cards/button-card) for this, you can configure it any way you want using CSS.

Example: 
![](https://raw.githubusercontent.com/custom-cards/bar-card/master/images/entities_example.png)
