### ISSUE TITLE
[ Feature Request ] Entity attributes

### ISSUE THREAD

**Issue by firstof9** [custom-cards/bar-card#93]
It would be nice if we could specify an `attribute` from the `entity` to use as the value, this would reduce the need for a template sensor specifically for things like battery levels.

**Comment by sarahmva** [comment]
This works for me:
      - entity: sensor.th_fridge_kitchen_right_battery
        name: Voltage Kitchen right
        attribute: battery_voltage

**Comment by firstof9** [comment]
Not sure why this wasn't closed when it was added lol
