### ISSUE TITLE
Entities are shown as missing during loading

### ISSUE THREAD

**Issue by chemelli74** [custom-cards/bar-card#96]
Hi, please review this comment to make the card compliant with the new load system:

[0.111.0 Brother says entity doesn't exist during lovelace loading](https://github.com/home-assistant/frontend/issues/6150#issuecomment-663053660)

Simone

**Comment by Gluwc** [comment]
Are you sure the entities are actually available? I don't think this is related to this card.

**Comment by chemelli74** [comment]
> Are you sure the entities are actually available? I don't think this is related to this card.

Yes, after 1 minute from the restart, they works fine.
If you review the comment above, a dev pointed out a specific line of your code to be updated for the new HA behavior.

Thx,

Simone

**Comment by Gluwc** [comment]
The line in the code just points to the error it displays. There's not much I can do if the entity doesn't exist in Home Assistant.

**Comment by chemelli74** [comment]
> The line in the code just points to the error it displays. There's not much I can do if the entity doesn't exist in Home Assistant.

I'll try to explain better.

Entities exists and works fine, once loading is complete.

During HA load since a few version, there is a new load mechanism that shows the message" Home Assitant is starting, not everything may be available yet" on all entities until the corresponding integration is loaded" (see Neato in the screenshot below).

![image](https://user-images.githubusercontent.com/57354320/84492911-319b5200-aca7-11ea-82fd-87fef26729b1.png)

Same happens on Brother if I put those in a entities built-in card.

Unfortunately the new mechanism is not handled by for bar-card and it shows that the entity is missing as  you can see in the screenshot above.

An HA core dev pointed out that your code should be updated to the new behavior.

Hope I explained clearly now, if not  feel free to ask for more details.

Simone

**Comment by chemelli74** [comment]
Any news ?

**Comment by chemelli74** [comment]
Did you get time to check this issue ?

Simone

**Comment by Gluwc** [comment]
I'm very sorry but I currently don't have time to work on this.

**Comment by chemelli74** [comment]
@Gluwc, do you think you can take a look ? ;-)

Thx

Simone

**Comment by chemelli74** [comment]
@Gluwc do you mind checking this line of code: https://github.com/custom-cards/bar-card/blob/3bf47962bf4e1985c90cffe5a0358d0592ce707b/src/bar-card.ts#L129

Seems a easy solution after all ;-)

Simone

**Comment by chemelli74** [comment]
@Gluwc, are you still maintaining this card ?

Thx in advance for your feedback.

Simone

**Comment by chemelli74** [comment]
Closing, not maintained. Repo should be marked as "archived".

Simone
